### ISSUE TITLE
Skip identity prompt when logged in

### ISSUE THREAD

**Issue by jacebrowning** [citizenlabsgr/mittens#66]
Mittens can jump right to checking registration status.

This should also fix #65.

**Comment by diiq** [comment]
Note: don't do this without first adding logout!

(In fact, with the app *as it stands now*, I expect handing your device off to someone else is more likely than revisiting the page to see if you're still registered.)

**Comment by diiq** [comment]
See https://fsty.io/v/79aMHdY

**Comment by jacebrowning** [comment]
We've pivoted to https://app.michiganelections.io providing the logged-in ballot-tracking experience so I think we can close this.
